Add user's roles by Rolify Gem.
FindHussnain/twitter_lite pull request #1
Opened 2021-12-03 06:51 UTC by FindHussnain

2021-12-03 08:40 UTC, aliammaar commented on Gemfile
> +gem 'will_paginate', '~> 3.3', '>= 3.3.1'
use pagy gem instead of this.

2021-12-03 08:41 UTC, aliammaar commented on app/controllers/application_controller.rb
> +  end
adjust indentation please

2021-12-03 08:42 UTC, aliammaar commented on app/controllers/articles_controller.rb
> +	before_action :check_user, only:[:new, :edit, :update, :destroy]
how about `authenticate_user` instead of `check_user` ?

2021-12-03 08:43 UTC, aliammaar commented on app/controllers/sessions_controller.rb
> +class SessionsController < ApplicationController
Update your sublime settings.

We use 2 space for indentation.

```
{
	"added_words":
	[
		"online"
	],
	"bold_folder_labels": true,
	"caret_style": "wide",
	"color_scheme": "Packages/Color Scheme - Default/Monokai.sublime-color-scheme",
	"default_line_ending": "unix",
	"draw_white_space": "all",
	"enable_tab_scrolling": false,
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": false,
	"fallback_encoding": "UTF-8",
	"find_selected_text": true,
	"font_face": "Operator Mono",
	"font_options":
	[
		"subpixel_antialias"
	],
	"font_size": 17,
	"highlight_line": true,
	"ignored_packages":
	[
		"Markdown",
		"Vintage",
	],
	"line_padding_bottom": 1,
	"open_files_in_new_window": false,
	"rulers":
	[
		120
	],
	"save_on_focus_lost": true,
	"shift_tab_unindent": true,
	"tab_size": 2,
	"theme": "Default.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"use_tab_stops": true,
	"word_wrap": true,
}

```

2021-12-03 08:44 UTC, aliammaar commented on app/controllers/sessions_controller.rb
> +	   		flash[:success] = "You have logged in"
You are logged in successfully.

2021-12-03 08:44 UTC, aliammaar commented on app/controllers/sessions_controller.rb
> +			flash.now[:danger] = "There was something wrong with your login information"
Invalid email or password.

2021-12-03 08:45 UTC, aliammaar commented on app/controllers/sessions_controller.rb
> + 	end
newline before `def destroy` ?

2021-12-03 08:45 UTC, aliammaar commented on app/controllers/users_controller.rb
> +	end
newline?

2021-12-03 08:45 UTC, aliammaar commented on app/controllers/users_controller.rb
> +	def create
indentation again.

2021-12-03 08:46 UTC, aliammaar commented on app/controllers/users_controller.rb
> +	def edit
newline ?

also make it one-liner method `def edit; end`.

2021-12-03 08:47 UTC, aliammaar commented on app/controllers/users_controller.rb
> +		@user = User.find(params[:id])
DRY this controller and others where needed by adding a before action.

```ruby
before_action :set_user, only [:show, :edit] .....

def set_user 
  @user = User.find(params[:id])
end
```

2021-12-03 08:49 UTC, aliammaar commented on app/models/role.rb
> +
remove 1 extra newline.

2021-12-06 09:16 UTC, aliammaar requested changes

2021-12-06 17:23 UTC, FindHussnain commented on Gemfile
> +gem 'bootstrap-will_paginate', '~> 1.0'
no :disappointed:

2021-12-06 19:03 UTC, FindHussnain commented on Gemfile
> +gem 'will_paginate', '~> 3.3', '>= 3.3.1'
Done

2021-12-22 10:10 UTC, aliammaar requested changes

2021-12-22 10:10 UTC, aliammaar commented on Gemfile
> +gem 'bootstrap-will_paginate', '~> 1.0'
We can remove it ?

2021-12-22 10:10 UTC, aliammaar commented on app/controllers/application_controller.rb
> +	include Pagy::Backend
looks like `4 spaces` indentation? We follow 2 spaces pattern.

2021-12-22 10:10 UTC, aliammaar commented on app/controllers/articles_controller.rb
> +	def article_params
newline ?

2021-12-22 10:10 UTC, aliammaar commented on app/controllers/articles_controller.rb
> +		@article = Article.find(params[:id])
`4 spaces` indentation?

2021-12-22 10:10 UTC, aliammaar commented on app/controllers/users_controller.rb
> +	end
`4 spaces` indentation?

2021-12-22 10:10 UTC, aliammaar commented on app/models/application_record.rb
> +	self.abstract_class = true
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/models/user.rb
> +	rolify
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/articles/index.html.erb
> +	<%= raw pagy_bootstrap_nav(@pagy) %>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/articles/show.html.erb
> +	<% if @article.user %>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/layouts/_navigation.html.erb
> +	<div class="container-fluid">
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/layouts/application.html.erb
> +	<head>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/sessions/new.html.erb
> +<%#= render 'shared/errors', obj: @user %>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/shared/_article.html.erb
> +<% obj.each do |article| %>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/shared/_errors.html.erb
> +	<div class="row">
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/users/index.html.erb
> +<h1 align="center">All Users</h1>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/users/show.html.erb
> +		<%= gravatar_for @user, size: 150%>
make it 2 spaces.

2021-12-22 10:10 UTC, aliammaar commented on app/views/users/show.html.erb
> +		<%= gravatar_for @user, size: 150%>
also use `()` when you calling a method.

2021-12-23 16:40 UTC, closed without merging